### ISSUE TITLE
BasicVariant fails to compile with Clang 6 and stdlibc++ 9.4.0

### ISSUE THREAD

**Issue by MikeLankamp-TomTom** [ndsev/zserio-cpp17#49]
Compiling the generated NDS.Live's schema with the newly released v0.1.0 generator yields some weird compile errors.
I'm using Clang 6 with GCC 9.4.0's stdlibc++.

Full error log is attached (see [full-error-log.txt](https://github.com/user-attachments/files/17993592/full-error-log.txt)), but the core of it is this:
```
/usr/local/pkg/gcc/include/c++/variant:156:13:  error: cannot cast private base class 'std::__detail::__variant::_Variant_storage<false, ...>' to 'std::variant<...>'
...
usr/local/pkg/gcc/include/c++/variant:1229:7: note: constrained by private inheritance here
    : private __detail::__variant::_Variant_base<_Types...>,
```
This is ultimately called from here:
```
zserio-2.15-cpp17/zserio/Variant.h:310:36: note: in instantiation of function template specialization 'std::variant<...>::emplace<...>' requested here
            return m_data.template emplace<static_cast<size_t>(I)>(std::forward<ARGS>(args)...);
```

Best I can make out from the error log and looking at stdlibc++'s `<variant>`, the following happens:
* `std::variant` privately inherits from `std::__detail::__variant::_Variant_storage`.
* `_Variant_storage::_M_reset_impl` invokes `std::__variant_cast` to get a reference to the top-level `std::variant<...>` from `*this`, in order to use `visit` and clean up the stored object.
* `std::__variant_cast` is declared as a friend in `std::variant` (to get around the private inheritance).

Despite the friend declaration, the compiler still complains about the cast-from-private-base-class. I do not understand why.

I could not reproduce this myself in a smaller standalone test case using `std::variant::emplace` as used in `BasicVariant`, so there must be something about its usage in zserio that I do not yet understand.

**Comment by Mi-La** [comment]
I'm not sure if we really need to support old compilers - even the old C++ generator states that it supports Clang 11.0 (and probably newer) - https://github.com/ndsev/zserio/blob/master/compiler/extensions/cpp/README.md#supported-compilers.
Currently we test the c++17 extension with Gcc-11, Clang-14 and Clang-18 - see https://github.com/ndsev/zserio-cpp17/blob/master/.github/workflows/build_linux_cpp.yml.

**Comment by MikeLankamp-TomTom** [comment]
Fair point. However, I'm seeing this generic error in `<variant>` reported in other places, e.g.:
* https://root-forum.cern.ch/t/variant-including-rresultptr-doesnt-compile-with-gcc-9-1/35029 (GCC 9.1, stdlibc++ 9.1.0).
* https://alice-talk.web.cern.ch/t/qualitycontrol-not-compiling-under-gcc9/619/7 (GCC 9)

Either way, we're not on one of the latest compilers, and the fact that the error is triggered depending on usage, makes me wonder if we can't try to fix it in the zserio runtime so it can work on our setup.

I might also try to reproduce with a newer compiler and same stdlibc++, but that might take some time for me to set up. I'm still not sure if it's a compiler issue, or stdlibc++ issue, or both.

**Comment by Mi-La** [comment]
To me it seems like a problem with the stdlibc++ 9.x, maybe only in combination with newer compilers.
We can leave this issue open and try to fix it when everything is implemented - in the worst case we can write the zserio `Variant` completely without usage of `std::variant`, but it was quite handy to use std::variant inside and moreover `std::variant` usually has some space optimizations directly in the STL library.

In any case we should decide first which compilers / STD library versions we need to support.

**Comment by MikeLankamp-TomTom** [comment]
Some more info: I can reproduce it in a minimal isolated test case. For some reason, it seems to depend on the types of the variant:
```
int main()
{
    //using T = float;                       // OK
    //using T = std::array<bool, 2>;         // OK
    //using T = bool[2];                     // OK
    //using T = int*;                        // OK
    //using T = std::reference_wrapper<int>; // OK
    //using T = std::unique_ptr<int>;        // FAIL
    //using T = std::shared_ptr<int>;        // FAIL
    //using T = std::set<int>;               // FAIL
    //using T = std::map<int, int>;          // FAIL
    //using T = std::vector<float>;          // FAIL
    //using T = std::string;                 // FAIL

    std::variant<bool, T> x;
    x.emplace<0>(true);
}
```
For some reason, it seems that any type that uses dynamic (de)allocation causes this problem.

**Comment by MikeLankamp-TomTom** [comment]
Update: apparently this is related to Clang-6: https://github.com/llvm/llvm-project/issues/32569. We're discussing upgrading the compiler to properly support C++17. I guess it's fine to close this as "compiler too old, not supported".

**Comment by Mi-La** [comment]
Thanks for the investigation and the link to clang issue! We will close it for now but feel free to reopen if it will be a problem.

**Comment by Mi-La** [comment]
compiler too old
